export default [
  {
    files: ["static/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        fetch: "readonly",
        caches: "readonly",
        self: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        requestIdleCallback: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        AbortController: "readonly",
        EventSource: "readonly",
        Notification: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        history: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        atob: "readonly",
        btoa: "readonly",
        structuredClone: "readonly",
        matchMedia: "readonly",
        getComputedStyle: "readonly",
        DISCIPLINES: "readonly",
        ValueMetrics: "readonly",
        clients: "readonly",
        registration: "readonly",
        skipWaiting: "readonly",
        importScripts: "readonly",
      },
    },
    rules: {
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-unreachable": "error",
      "no-cond-assign": ["error", "except-parens"],
      "getter-return": "error",
      "no-func-assign": "error",
      "no-dupe-else-if": "error",
      "no-self-assign": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-unused-vars": "off",
      "no-empty": "off",
      "no-undef": "off",
      "no-redeclare": "off",
    },
  },
];
